/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductStockjsonldConsume model module.
 * @module model/ProductStockjsonldConsume
 * @version 0.0.6
 */
class ProductStockjsonldConsume {
    /**
     * Constructs a new <code>ProductStockjsonldConsume</code>.
     * @alias module:model/ProductStockjsonldConsume
     */
    constructor() { 
        
        ProductStockjsonldConsume.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductStockjsonldConsume</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductStockjsonldConsume} obj Optional instance to populate.
     * @return {module:model/ProductStockjsonldConsume} The populated <code>ProductStockjsonldConsume</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductStockjsonldConsume();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @context
 */
ProductStockjsonldConsume.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
ProductStockjsonldConsume.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
ProductStockjsonldConsume.prototype['@type'] = undefined;






export default ProductStockjsonldConsume;

